version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "3000:3000"
    environment:
      - FLASK_APP=src/app.py
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://gitpod:postgres@db:5432/example
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: gitpod
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
